version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_POLLING_INTERVAL_MS=500
      - WDS_SOCKET_PORT=3000
      - WDS_SOCKET_HOST=localhost
      - FAST_REFRESH=false
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]