FROM node:18-alpine

WORKDIR /app

COPY package.json .
RUN npm install

COPY . .

# Force polling inside the container as a fallback
ENV CHOKIDAR_USEPOLLING=true

CMD ["sh", "-c", "CHOKIDAR_USEPOLLING=true npm run start"]