name: Deploy to Yandex Cloud (existing VM)

on:
  push:
    branches:
      - master

env:
  REGISTRY_ID: 'crp7as3gv0vo9o5caba8'   # ваш ID реестра (можно оставить как есть)
  IMAGE_NAME: 'my-frontend-app'
  VM_IP: '158.160.5.25'
  VM_USER: 'admin123'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.VM_IP }}
          username: ${{ env.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Остановить и удалить старый контейнер, если есть
            docker stop my-app || true
            docker rm my-app || true
            # Забрать последний образ
            docker pull cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            # Запустить новый контейнер
            docker run -d -p 80:80 --name my-app cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}