name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - master

env:
  REGISTRY_ID: 'crp7as3gv0vo9o5caba8'   # например crpXXXXXX
  FOLDER_ID: 'b1g500gut4abvcd5ndkp'    # например b1gXXXXXX
  VM_NAME: 'my-app-vm'
  IMAGE_NAME: 'my-frontend-app'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate YC CLI using JSON key
        run: |
          echo '${{ secrets.YC_SA_JSON_CREDENTIALS }}' > key.json
          yc config set service-account-key key.json
          yc config set folder-id ${{ env.FOLDER_ID }}

      - name: Docker login via YC
        run: |
          yc container registry configure-docker --profile=default

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to VM
        uses: yc-actions/yc-coi-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ env.FOLDER_ID }}
          vm-name: ${{ env.VM_NAME }}
          vm-service-account-id: ${{ secrets.YC_SA_ID }}
          image: cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          vm-cores: 2
          vm-memory: 2Gb
          vm-core-fraction: 20